apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-latest
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: require-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Containers must not run as root."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true

    - name: disallow-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Using the 'latest' image tag is not allowed."
        pattern:
          spec:
            containers:
              - image: "!*:latest"