---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAtaE9a9V4J6Z8aGJFTNWYA9NHRr3kbE7zfbipX4+RrS5u5sKpJjH5hGDewBqKsyRZQNt2oOWZLu0o/U3rWphP5qysMf1QZ8zwncirI0fLNtsyV6qUvOnDTw20+jOXVvRIdz8TfxI0YmYJEHZdphU8B8dc0jagzHzCSnbpRWrvN/TDKZJvQPuD+gSqvHKxTPu6zZJTGU64m3HI+qEPgjqb7WJMoQNrOkptf1n11ewS+Kz4xk7R3sJVroIbhbi578a9q3xCRS/Ka/mciuUKv0dQ5+MRo6fJ783ESWgU+zsdzfFiym5bIS7HM3yhdHCPY0E0d228jJr5M0lUoz2C4qXaHnzPhbcO6OeAmUWUJMnvxJE+h4GNYSCTXl/on7xvr0eD4eHsXeqJvleFwZRQjPyJ61aMIRc41UcqvSEauD81hxfY40xaezBDiuRKwfDhu43zPVO75U7g1BQiDxsmnNnbRLpy+XFOERHABlRA42gz2NZP9UKVcnj3TT/n4hMWpYhF+UJZjK3IFXjdKgZp2hZnPjO7ffxyxj4t0Icu6oKdSWlow+j9nO74j18ucdUA5O8tw1Dgi2I8fF3QUw7zEWL58ek26gyGy8Z5T4GETc/Seqac2RxTtPR8732SjT1Kn9YbKW927Laf1c8swokkf7jAM4rhj0WsXvM1eEI8dRI517CNzq7E23UhXbrRwhXEEmO/Va1fYKwsVF0CNOeKa
    STRIPE_API_KEY: AgBoCNL8iCo7QehB2SygePUAeK9NNXAJD1pU8bFxEJACPrfE8XK6nPsMAoq11j6LnRXarvip0UuRd5SBXp2u6IxEn8nyvJkn2XbeznTcsz08o1r8bqupQhMl0hUcJepdJcpyEbTZuHkb+VZyEbFi3dtiN1gqlkGCQpQmxG134raiP+bX8asDNlkp3CgSIdPvCJxQwqvsHpFQyWZfnSF5Olm0y/KMtz/Fu93Ey6QuZKv6kB2MkowpcH+3NWelfqOlgrGxCZW1CREvwVgtogLAxYsZS5keOI8q5mvaYmYAHDBvUiLplDBWmikHhSCpICC4KFrSfaOKFg/GFzTXNBsaoKmHGCa0WMIHKuw3wHERgk/2uUj2OKOqYzKMmwMXf8NBCy5FgeHe9zLYMAMo8h3haBFTD7ccwvUbFxytOJYHsrlHXFsvX5NHwTXUmt/oNARKeMo5qX6r+ZPV5ruHEYi+qSVvkbCDBfYflK3gWJCUiUzOrWuTQ+Zh9muaxFLBs/q7zKYhzBW9lB/7oK1ahgwgDyA3II/EomU74QEh8WXcxeG6djpuSkYjm2wU4AdokwbLcyGQGVZfEXcU3qV6L+LdyQiGiXLh+/50YJiEQzRFCKCPGWrNSydb0qCcpRAkM3WsMBZrq3IvdRmLiJRswtFHXbpxxavWQniYWFybQYlabv5j+RxAy9LTjDrbXz/PYh9f4dX/W2EnySwD7bVvmhgE
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
